import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What CiteSeek stores, where it is stored, who else processes it, and how to delete it.",
};

/**
 * What happens to a document someone uploads.
 *
 * Written from the code rather than from a template. Every claim here is one the
 * repository can be checked against — the region is in `vercel.json`, the
 * retention window is `RETENTION_DAYS`, the cascade is one `DELETE` in
 * `lib/users/deletion.ts`, and "extracted text, not the file" is ADR 009. A
 * policy that says more than the system does is worse than no policy, because it
 * is the part a reader is entitled to rely on.
 *
 * The provider paragraph is deliberately the conservative reading. Google grants
 * paid-service data terms to customers in some regions even on unpaid quota, but
 * that follows the account's billing region and has not been confirmed for this
 * account. Until it is, the policy says what is certain and warns accordingly —
 * a privacy policy is the last place to state a protection you have not checked.
 */
export default function PrivacyPage() {
  return (
    <main id="main" className="mx-auto w-full max-w-2xl flex-1 px-6 py-12">
      <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
      <p className="text-muted-foreground mt-2 text-sm">
        Last updated 3 August 2026. This describes what the application actually
        does; if anything here disagrees with the code, the code is the bug.
      </p>

      <Section title="The short version">
        <p>
          CiteSeek stores the <strong>text extracted</strong> from documents you
          upload, never the original files. Everything is hosted in the EU.
          Answers are generated by Google&rsquo;s Gemini API, which means the
          text of your documents and your questions is sent to Google.{" "}
          <strong>
            This deployment runs on Google&rsquo;s free tier, so do not upload
            anything confidential.
          </strong>{" "}
          Deleting your account deletes everything, immediately and for real.
        </p>
      </Section>

      <Section title="What is stored">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Your account</strong> — the email address and profile name
            your sign-in provider gives us, and a session record.
          </li>
          <li>
            <strong>Extracted text</strong> — when you upload a document, it is
            parsed and the text is stored. The uploaded file itself is discarded
            once parsing finishes and is never written to disk or object
            storage.
          </li>
          <li>
            <strong>Passages and embeddings</strong> — the text split into
            chunks, each with a numeric vector used to find relevant passages.
            The vectors are derived from your text and are stored alongside it.
          </li>
          <li>
            <strong>Conversations</strong> — your questions, the answers, and
            which passages each answer cited.
          </li>
          <li>
            <strong>Usage counts</strong> — how many provider calls were made
            and how many tokens they used, kept for 30 days and then deleted.
            These carry no document or message content.
          </li>
        </ul>
        <p className="mt-3">
          Guests are the exception: a guest session is a signed cookie with a
          24-hour expiry and{" "}
          <strong>
            nothing about a guest is written to the database at all
          </strong>
          . A guest&rsquo;s conversation lives in their browser and is gone on
          reload.
        </p>
      </Section>

      <Section title="Where it is stored">
        <p>
          The application runs in Frankfurt (Vercel <code>fra1</code>) and the
          database is a Neon Postgres instance in the same region. Both are
          pinned in configuration rather than left to a default.
        </p>
      </Section>

      <Section title="Who else processes it">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Google (Gemini API)</strong> — receives the text of
            retrieved passages and your question in order to generate an answer,
            and receives document text in order to produce embeddings. See the
            warning below.
          </li>
          <li>
            <strong>Vercel</strong> — hosts the application and terminates
            requests.
          </li>
          <li>
            <strong>Neon</strong> — hosts the database.
          </li>
          <li>
            <strong>GitHub</strong> — only if you sign in with it, and only to
            confirm who you are.
          </li>
        </ul>
      </Section>

      <Section title="The provider caveat, stated plainly">
        <p>
          This deployment uses Google&rsquo;s <strong>free tier</strong>. Under
          the standard free-tier terms, Google may use submitted content to
          improve its services. A paid tier, or written data-processing terms,
          changes that — and until this deployment has one and this page says
          so, you should treat anything you upload as content you would be
          willing to share with a third party.
        </p>
        <p className="mt-3">
          That is why the demo workspace is read-only and seeded with a
          fictional document, and why this warning appears beside the upload
          control rather than only here.
        </p>
      </Section>

      <Section title="Deleting your data">
        <p>
          Deleting a document removes its text, its passages and their
          embeddings. Deleting your account removes the account, its workspaces,
          every document in them, every conversation, and every usage record —
          in one operation, with no soft-delete and no recovery window. You can
          do it yourself from the{" "}
          <Link href="/account" className="underline">
            account page
          </Link>
          .
        </p>
      </Section>

      <Section title="What is never done">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Document contents and message bodies are never written to logs.
          </li>
          <li>There is no analytics, advertising or third-party tracking.</li>
          <li>Nothing is sold or shared beyond the processors listed above.</li>
        </ul>
      </Section>

      <Section title="Contact">
        <p>
          This is a portfolio project rather than a company. Questions and
          erasure requests go through the repository linked from the{" "}
          <Link href="/" className="underline">
            home page
          </Link>
          .
        </p>
      </Section>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-medium">{title}</h2>
      <div className="text-muted-foreground mt-2 text-sm leading-relaxed">
        {children}
      </div>
    </section>
  );
}
