import type { ReactNode } from "react";
import type { Metadata } from "next";
import Link from "next/link";

import { REPOSITORY_URL } from "@/lib/links";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What CiteSeek stores, where it is stored, who else processes it, and how to delete it.",
};

/**
 * Every claim here is checkable against the repository: the region in
 * `vercel.json`, the window in `RETENTION_DAYS`, the cascade in
 * `lib/users/deletion.ts`, "extracted text, not the file" in ADR 009.
 *
 * The provider paragraph is the conservative reading on purpose — Google's
 * paid-service terms follow the account's billing region and this account has
 * not been checked. A policy is the last place to claim an unverified protection.
 */
export default function PrivacyPage() {
  return (
    <main
      id="main"
      className="mx-auto w-full max-w-2xl flex-1 px-4 py-12 sm:px-6"
    >
      <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
      <p className="text-muted-foreground mt-2 text-sm">
        Last updated 3 August 2026. This describes what the application actually
        does. If the two ever disagree, the application is what gets fixed —
        this page is a promise, not a disclaimer.
      </p>

      <Section title="The short version">
        <p>
          {/* The emphasis ends the clause, so no space follows the tag: one that
            did rendered as "extractedfrom", and Prettier collapses `{" "}` back
            into the space that gets dropped. */}
          CiteSeek stores{" "}
          <strong>the text extracted from documents you upload</strong>, never
          the original files. Everything is hosted in the EU. Answers are
          generated by Google&rsquo;s Gemini API, which means the text of your
          documents and your questions is sent to Google.{" "}
          <strong>
            This deployment runs on Google&rsquo;s free tier, so do not upload
            anything confidential.
          </strong>{" "}
          Deleting your account deletes everything, immediately and for real.
        </p>
      </Section>

      <Section title="What is stored">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Your account</strong> — the email address and profile name
            your sign-in provider gives us, and a session record.
          </li>
          <li>
            <strong>Extracted text</strong> — when you upload a document, it is
            parsed and the text is stored. The uploaded file itself is discarded
            once parsing finishes and is never written to disk or object
            storage.
          </li>
          <li>
            <strong>Passages and embeddings</strong> — the text split into
            chunks, each with a numeric vector used to find relevant passages.
            The vectors are derived from your text and are stored alongside it.
          </li>
          <li>
            <strong>Conversations</strong> — your questions, the answers, and
            which passages each answer cited.
          </li>
          <li>
            <strong>Usage counts</strong> — how many provider calls were made
            and how many tokens they used, kept for 30 days and then deleted.
            These carry no document or message content.
          </li>
        </ul>
        <p className="mt-3">
          Guests are the exception: a guest session is a signed cookie with a
          24-hour expiry and{" "}
          <strong>
            nothing about a guest is written to the database at all
          </strong>
          . A guest&rsquo;s conversation lives in their browser and is gone on
          reload.
        </p>
      </Section>

      <Section title="Where it is stored">
        <p>
          The application runs in Frankfurt (Vercel <code>fra1</code>) and the
          database is a Neon Postgres instance in the same region. Both are
          pinned in configuration rather than left to a default.
        </p>
      </Section>

      <Section title="Who else processes it">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Google (Gemini API)</strong> — receives the text of
            retrieved passages and your question in order to generate an answer,
            and receives document text in order to produce embeddings. See the
            warning below.
          </li>
          <li>
            <strong>Vercel</strong> — hosts the application and terminates
            requests.
          </li>
          <li>
            <strong>Neon</strong> — hosts the database.
          </li>
          <li>
            <strong>GitHub</strong> — only if you sign in with it, and only to
            confirm who you are.
          </li>
        </ul>
      </Section>

      <Section title="The provider caveat, stated plainly">
        <p>
          This deployment uses Google&rsquo;s <strong>free tier</strong>. Under
          the standard free-tier terms, Google may use submitted content to
          improve its services. A paid tier, or written data-processing terms,
          changes that — and until this deployment has one and this page says
          so, you should treat anything you upload as content you would be
          willing to share with a third party.
        </p>
        <p className="mt-3">
          That is why the demo workspace is read-only and seeded with a
          fictional document, and why this warning appears beside the upload
          control rather than only here.
        </p>
      </Section>

      <Section title="Deleting your data">
        <p>
          Deleting a document removes its text, its passages and their
          embeddings. Deleting your account removes the account, its workspaces,
          every document in them, every conversation, and every usage record —
          in one operation, with no soft-delete and no recovery window. You can
          do it yourself from the{" "}
          <Link href="/account" className="underline">
            account page
          </Link>
          .
        </p>
      </Section>

      <Section title="What is never done">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Document contents and message bodies are never written to logs.
          </li>
          <li>There is no analytics, advertising or third-party tracking.</li>
          <li>Nothing is sold or shared beyond the processors listed above.</li>
        </ul>
      </Section>

      <Section title="Contact">
        <p>
          This is a portfolio project rather than a company. Questions and
          erasure requests go through{" "}
          <a
            href={REPOSITORY_URL}
            className="underline"
            target="_blank"
            rel="noreferrer"
          >
            the repository
          </a>
          , which is linked in the footer of every page. You can also delete
          everything yourself from the{" "}
          <Link href="/account" className="underline">
            account page
          </Link>{" "}
          without asking anyone.
        </p>
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-medium">{title}</h2>
      <div className="text-muted-foreground mt-2 text-sm leading-relaxed">
        {children}
      </div>
    </section>
  );
}
