import type { ReactNode } from "react";
import type { Metadata } from "next";
import Link from "next/link";

import { REPOSITORY_URL } from "@/lib/links";
import { pageShell } from "@/components/ui/page-shell";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What CiteSeek stores, where it is stored, who else processes it, and how to delete it.",
};

/**
 * Every claim here is checkable against the repository: the region in
 * `vercel.json`, the window in `RETENTION_DAYS`, the cascade in
 * `lib/users/deletion.ts`, "extracted text, not the file" in ADR 009.
 *
 * The provider paragraph tracks the tier the deployment is actually on, and
 * changes in the same commit as the tier — never before it. A policy is the last
 * place to claim a protection that is not live yet (ADR 025).
 */
export default function PrivacyPage() {
  return (
    <main id="main" className={pageShell("2xl", "flex-1")}>
      <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
      <p className="text-muted-foreground mt-2 text-sm">
        Last updated 3 August 2026. This describes what the application actually
        does. If the two ever disagree, the application is what gets fixed —
        this page is a promise, not a disclaimer.
      </p>

      <Section title="The short version">
        <p>
          {/* The emphasis ends the clause, so no space follows the tag: one that
            did rendered as "extractedfrom", and Prettier collapses `{" "}` back
            into the space that gets dropped. */}
          CiteSeek stores{" "}
          <strong>the text extracted from documents you upload</strong>, never
          the original files. Everything is hosted in the EU. Answers are
          generated by Google&rsquo;s Gemini API, which means the text of your
          documents and your questions is sent to Google.{" "}
          <strong>
            This deployment is on Google&rsquo;s paid tier, so that content is
            not used to train or improve their models.
          </strong>{" "}
          Deleting your account deletes everything on our servers, immediately
          and for real. Local mode is the exception, and deliberately so: those
          documents stay in your browser, so you delete them there.
        </p>
      </Section>

      <Section title="What is stored">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Your account</strong> — the email address and profile name
            your sign-in provider gives us, and a session record.
          </li>
          <li>
            <strong>Extracted text</strong> — when you upload a document, it is
            parsed and the text is stored. The uploaded file itself is discarded
            once parsing finishes and is never written to disk or object
            storage.
          </li>
          <li>
            <strong>Passages and embeddings</strong> — the text split into
            passages, each with a numeric vector used to find relevant ones. The
            vectors are derived from your text and are stored alongside it.
          </li>
          <li>
            <strong>Conversations</strong> — your questions, the answers, and
            which passages each answer cited.
          </li>
          <li>
            <strong>Usage counts</strong> — how many provider calls were made
            and how many tokens they used, kept for 30 days and then deleted.
            These carry no document or message content.
          </li>
        </ul>
        <p className="mt-3">
          Guests are the exception: a guest session is a signed cookie with a
          24-hour expiry and{" "}
          <strong>
            nothing about a guest is written to the database at all
          </strong>
          . A guest&rsquo;s conversation lives in their browser and is gone on
          reload.
        </p>
      </Section>

      <Section title="Where it is stored">
        <p>
          The application runs in Frankfurt (Vercel <code>fra1</code>) and the
          database is a Neon Postgres instance in the same region. Both are
          pinned in configuration rather than left to a default.
        </p>
      </Section>

      <Section title="Local mode, which stores nothing on our servers">
        <p>
          Documents added in{" "}
          <a href="/local" className="underline">
            local mode
          </a>{" "}
          are stored <strong>in your browser</strong>, not on our servers. They
          are never uploaded, no processor below receives them, and none of the
          hosting above applies to them.
        </p>
        <p className="mt-3">
          One thing does leave: your browser downloads two models from{" "}
          <strong>Hugging Face</strong>, which sees those requests the way any
          website you visit does — about 128 MB to index a document, and about
          756 MB more before it can answer one, each fetched once and then
          cached. <strong>No document text is sent</strong>: they are downloads
          of public files, in that direction only.
        </p>
        <p className="mt-3">
          Two consequences worth being direct about. That storage belongs to{" "}
          <strong>the browser profile, not to your account</strong> — signing
          out does not clear it, and anyone else using this browser on this
          computer can open local mode and read what is there. And{" "}
          <strong>deleting your account does not remove it</strong>, because the
          deletion runs on our servers and this data never reached them.
        </p>
        {/* A plain anchor, not <Link>: a client-side navigation reuses this
            document's CSP, and /local needs the WASM directives its own
            response carries (ADR 028, ADR 030). */}
        <p className="mt-3">
          Delete it yourself with <strong>Delete everything</strong> on the{" "}
          <a href="/local" className="underline">
            local mode page
          </a>
          . That removes the documents, their passages and their embeddings from
          this browser, with no recovery.
        </p>
      </Section>

      <Section title="Who else processes it">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Google (Gemini API)</strong> — receives the text of
            retrieved passages and your question in order to generate an answer,
            and receives document text in order to produce embeddings. See the
            warning below.
          </li>
          <li>
            <strong>Vercel</strong> — hosts the application and terminates
            requests.
          </li>
          <li>
            <strong>Neon</strong> — hosts the database.
          </li>
          <li>
            <strong>GitHub or Google</strong> — whichever you sign in with, and
            only to confirm who you are. Signing in with Google puts Google on
            this list twice, for two unrelated reasons.
          </li>
        </ul>
      </Section>

      <Section title="What Google may do with it">
        <p>
          This deployment runs on Google&rsquo;s <strong>paid tier</strong>,
          billed from an account in the EEA. Under those terms Google does not
          use submitted prompts or uploaded content to train or improve its
          models; it processes them to return an answer and for the retention
          their terms define, and nothing else.
        </p>
        <p className="mt-3">
          Until August 2026 this ran on the free tier, whose terms do allow
          submitted content to be used for product improvement, and this page
          said so. The tier changed because a policy that has to ask people not
          to upload anything sensitive is a request rather than a protection.
        </p>
        <p className="mt-3">
          What has not changed: the text still leaves this application and
          reaches Google, and no policy makes that untrue. The demo workspace is
          still read-only and seeded with a fictional document.
        </p>
      </Section>

      <Section title="Deleting your data">
        <p>
          Deleting a document removes its text, its passages and their
          embeddings. Deleting your account removes the account, its workspaces,
          every document in them, every conversation, and every usage record —
          in one operation, with no soft-delete and no recovery window. You can
          do it yourself from the{" "}
          <Link href="/account" className="underline">
            account page
          </Link>
          .
        </p>
        <p className="mt-3">
          It does not reach documents stored in your browser by local mode,
          which never left your machine for us to delete. Those are removed from
          the local mode page.
        </p>
      </Section>

      <Section title="What is never done">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Document contents and message bodies are never written to logs.
          </li>
          <li>There is no analytics, advertising or third-party tracking.</li>
          <li>Nothing is sold or shared beyond the processors listed above.</li>
        </ul>
      </Section>

      <Section title="Contact">
        <p>
          This is a portfolio project rather than a company. Questions and
          erasure requests go through{" "}
          <a
            href={REPOSITORY_URL}
            className="underline"
            target="_blank"
            rel="noreferrer"
          >
            the repository
          </a>
          , which is linked in the footer of every page. You can also delete
          everything yourself from the{" "}
          <Link href="/account" className="underline">
            account page
          </Link>{" "}
          without asking anyone.
        </p>
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-medium">{title}</h2>
      <div className="text-muted-foreground mt-2 text-sm leading-relaxed">
        {children}
      </div>
    </section>
  );
}
