import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

/** The PNGs are generated by hand and committed, so nothing rebuilds them when
 * the palette moves. This fails instead of shipping the wrong blue. */

const MARK = readFileSync(join(import.meta.dirname, "mark.svg"), "utf8");
const CSS = readFileSync(
  join(import.meta.dirname, "..", "..", "app", "globals.css"),
  "utf8",
);

function lightToken(name: string): string {
  const match = new RegExp(`^\\s*${name}:\\s*(.+);\\s*$`, "m").exec(
    CSS.slice(CSS.indexOf(":root {")),
  );

  expect(match, `no ${name} in the light palette`).not.toBeNull();
  return match![1]!.trim();
}

describe("the brand mark against the palette", () => {
  it("is drawn in the light theme's primary", () => {
    expect(MARK).toContain(`fill: ${lightToken("--primary")}`);
  });

  it("draws the glyph in the colour that primary is legible against", () => {
    expect(MARK).toContain(`stroke: ${lightToken("--primary-foreground")}`);
  });

  // One file cannot follow a theme, and a tab strip is as often light as dark.
  it("names no dark-mode colour it could not honour", () => {
    expect(MARK).not.toContain("prefers-color-scheme");
  });

  // An attribute would beat the generator's override.
  it("sets the corner radius in CSS, not as an attribute", () => {
    expect(MARK).toMatch(/\.ground\s*\{[^}]*rx:/);
    expect(MARK).not.toMatch(/<rect[^>]*\srx=/);
  });
});
